server {
    listen 80;
    server_name nerkhbaan.ir;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/nerkhbaan-acme;
        default_type text/plain;
    }

    location / {
        return 308 https://nerkhbaan.ir$request_uri;
    }
}
